// Catalog for the TV app. Each title: id, title, type ('movie'|'show'|'sports'|'kids'),
// year, length (runtime or seasons), genre, emoji, poster/backdrop gradients,
// desc, owned (Library), price (Store).
export const TITLES = [
  // ---------- TV shows ----------
  {
    id: 'severance', title: 'Severance', type: 'show', year: 2025, length: '2 Seasons',
    genre: 'Thriller', rating: 'TV-MA', emoji: '🧠',
    poster: 'linear-gradient(165deg,#0e3b4d,#0a1c2e 70%)',
    backdrop: 'linear-gradient(160deg,#14546e,#0a1c2e 55%,#050d16)',
    desc: 'Mark leads a team at Lumon Industries, whose employees have undergone a severance procedure that surgically divides their memories between work and personal life.',
    owned: true, price: 4.99, featured: true,
  },
  {
    id: 'ted-lasso', title: 'Ted Lasso', type: 'show', year: 2023, length: '3 Seasons',
    genre: 'Comedy', rating: 'TV-MA', emoji: '⚽',
    poster: 'linear-gradient(165deg,#1c7a4e,#0d3b6b)',
    backdrop: 'linear-gradient(160deg,#27a568,#0d3b6b 60%,#071f38)',
    desc: 'An American football coach is hired to manage a British soccer team — despite having no experience. What he lacks in knowledge, he makes up for in optimism.',
    owned: true, price: 4.99,
  },
  {
    id: 'slow-horses', title: 'Slow Horses', type: 'show', year: 2024, length: '4 Seasons',
    genre: 'Spy Drama', rating: 'TV-MA', emoji: '🕵️',
    poster: 'linear-gradient(165deg,#5c5346,#2b2620)',
    backdrop: 'linear-gradient(160deg,#7a6f5c,#2b2620 60%,#14110d)',
    desc: 'A team of MI5 rejects exiled to Slough House stumble into the middle of dangerous espionage plots, led by the brilliant but obnoxious Jackson Lamb.',
    owned: false, price: 4.99,
  },
  {
    id: 'foundation', title: 'Foundation', type: 'show', year: 2025, length: '3 Seasons',
    genre: 'Sci-Fi', rating: 'TV-14', emoji: '🌌',
    poster: 'linear-gradient(165deg,#3b2d7a,#16102e)',
    backdrop: 'linear-gradient(160deg,#54409e,#16102e 60%,#0a0718)',
    desc: 'A band of exiles discovers that the only way to save the Galactic Empire from destruction is to defy it. Based on Isaac Asimov’s novels.',
    owned: false, price: 4.99,
  },
  {
    id: 'silo', title: 'Silo', type: 'show', year: 2024, length: '2 Seasons',
    genre: 'Sci-Fi', rating: 'TV-MA', emoji: '🏙️',
    poster: 'linear-gradient(165deg,#6b5a2e,#2c2410)',
    backdrop: 'linear-gradient(160deg,#96803f,#2c2410 60%,#151006)',
    desc: 'Thousands live in a giant underground silo, told the outside world is toxic. When an engineer starts asking questions, everything unravels.',
    owned: false, price: 4.99,
  },
  {
    id: 'shrinking', title: 'Shrinking', type: 'show', year: 2024, length: '2 Seasons',
    genre: 'Comedy', rating: 'TV-MA', emoji: '🛋️',
    poster: 'linear-gradient(165deg,#2e6b8a,#173246)',
    backdrop: 'linear-gradient(160deg,#3f8eb5,#173246 60%,#0b1a24)',
    desc: 'A grieving therapist starts breaking the rules and telling his clients exactly what he thinks — with chaotic results for everyone involved.',
    owned: false, price: 4.99,
  },
  // ---------- Movies ----------
  {
    id: 'kotfm', title: 'Killers of the Flower Moon', type: 'movie', year: 2023, length: '3 h 26 min',
    genre: 'Crime', rating: 'R', emoji: '🌼',
    poster: 'linear-gradient(165deg,#8a3b2e,#33120c)',
    backdrop: 'linear-gradient(160deg,#b5523d,#33120c 60%,#180805)',
    desc: 'Members of the Osage Nation are murdered one by one after oil is discovered on their land, sparking a landmark FBI investigation.',
    owned: false, price: 19.99,
  },
  {
    id: 'napoleon', title: 'Napoleon', type: 'movie', year: 2023, length: '2 h 38 min',
    genre: 'Epic', rating: 'R', emoji: '🎖️',
    poster: 'linear-gradient(165deg,#1e3a5c,#0b1524)',
    backdrop: 'linear-gradient(160deg,#2d5482,#0b1524 60%,#050a12)',
    desc: 'An epic detailing the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power.',
    owned: false, price: 19.99,
  },
  {
    id: 'coda', title: 'CODA', type: 'movie', year: 2021, length: '1 h 51 min',
    genre: 'Drama', rating: 'PG-13', emoji: '🎶',
    poster: 'linear-gradient(165deg,#c98a2e,#5c3410)',
    backdrop: 'linear-gradient(160deg,#e8ab45,#5c3410 60%,#2e1a08)',
    desc: 'The only hearing member of a deaf family discovers a gift for singing and must choose between her family’s fishing business and her dreams.',
    owned: true, price: 14.99,
  },
  {
    id: 'finch', title: 'Finch', type: 'movie', year: 2021, length: '1 h 55 min',
    genre: 'Sci-Fi', rating: 'PG-13', emoji: '🤖',
    poster: 'linear-gradient(165deg,#b06a2c,#402508)',
    backdrop: 'linear-gradient(160deg,#d98f3d,#402508 60%,#201203)',
    desc: 'On a post-apocalyptic Earth, a dying inventor builds a robot to protect his beloved dog, and the unlikely trio heads west.',
    owned: false, price: 14.99,
  },
  {
    id: 'greyhound', title: 'Greyhound', type: 'movie', year: 2020, length: '1 h 31 min',
    genre: 'War', rating: 'PG-13', emoji: '⚓',
    poster: 'linear-gradient(165deg,#2e4a5c,#0e1c26)',
    backdrop: 'linear-gradient(160deg,#40667e,#0e1c26 60%,#070e13)',
    desc: 'A first-time captain leads a convoy of Allied ships across the treacherous “Black Pit” of the North Atlantic, hunted by U-boats.',
    owned: true, price: 14.99,
  },
  {
    id: 'tetris', title: 'Tetris', type: 'movie', year: 2023, length: '1 h 58 min',
    genre: 'Drama', rating: 'R', emoji: '🕹️',
    poster: 'linear-gradient(165deg,#7a2e8a,#2c0f38)',
    backdrop: 'linear-gradient(160deg,#a03fb5,#2c0f38 60%,#15071c)',
    desc: 'The unbelievable true story of how one of the world’s most popular video games found its way from behind the Iron Curtain to players everywhere.',
    owned: false, price: 14.99,
  },
  {
    id: 'argylle', title: 'Argylle', type: 'movie', year: 2024, length: '2 h 19 min',
    genre: 'Action', rating: 'PG-13', emoji: '🐱',
    poster: 'linear-gradient(165deg,#8a2e5c,#380f24)',
    backdrop: 'linear-gradient(160deg,#b53f7d,#380f24 60%,#1c0712)',
    desc: 'A reclusive spy novelist is drawn into real-world espionage when the plots of her books start mirroring a real crime syndicate.',
    owned: false, price: 19.99,
  },
  {
    id: 'fly-me-to-the-moon', title: 'Fly Me to the Moon', type: 'movie', year: 2024, length: '2 h 12 min',
    genre: 'Comedy', rating: 'PG-13', emoji: '🌙',
    poster: 'linear-gradient(165deg,#2e6b8a,#12293a)',
    backdrop: 'linear-gradient(160deg,#4192bd,#12293a 60%,#09141d)',
    desc: 'A marketing maven is hired to “sell” the Moon landing — and to stage a fake backup version just in case. Sparks fly with the launch director.',
    owned: false, price: 19.99,
  },
  // ---------- Sports ----------
  {
    id: 'mls-pass', title: 'MLS Season Pass', type: 'sports', year: 2026, length: 'Live',
    genre: 'Soccer', rating: 'Live', emoji: '⚽',
    poster: 'linear-gradient(165deg,#c22e4a,#4a0e1c)',
    backdrop: 'linear-gradient(160deg,#e83d5c,#4a0e1c 60%,#24070e)',
    desc: 'Every MLS match, live and on demand, with no blackouts. Inter Miami CF vs. LA Galaxy tonight at 7:30 PM ET.',
    owned: false, price: 12.99, live: true,
  },
  {
    id: 'fnb-yankees', title: 'Friday Night Baseball', type: 'sports', year: 2026, length: 'Live',
    genre: 'Baseball', rating: 'Live', emoji: '⚾',
    poster: 'linear-gradient(165deg,#2e5c8a,#102438)',
    backdrop: 'linear-gradient(160deg,#3f7dbd,#102438 60%,#08121c)',
    desc: 'Yankees vs. Red Sox under the lights. Live every Friday, only on Apple TV+.',
    owned: false, price: 0, live: true,
  },
  {
    id: 'mls-cup', title: 'MLS Cup Playoffs', type: 'sports', year: 2025, length: '12 Matches',
    genre: 'Soccer', rating: 'Live', emoji: '🏆',
    poster: 'linear-gradient(165deg,#8a6b2e,#33270e)',
    backdrop: 'linear-gradient(160deg,#b8943f,#33270e 60%,#191307)',
    desc: 'Relive every dramatic moment of the Audi MLS Cup Playoffs, from first-round upsets to the final whistle.',
    owned: true, price: 0,
  },
  // ---------- Kids (bright gradients) ----------
  {
    id: 'snoopy-space', title: 'Snoopy in Space', type: 'kids', year: 2021, length: '2 Seasons',
    genre: 'Kids', rating: 'TV-Y', emoji: '🚀',
    poster: 'linear-gradient(165deg,#4fc3f7,#7c4dff)',
    backdrop: 'linear-gradient(160deg,#6fd3ff,#7c4dff 60%,#3d2a8a)',
    desc: 'Blast off with Snoopy as he fulfills his dream of becoming a NASA astronaut, joined by Charlie Brown and the Peanuts gang.',
    owned: true, price: 2.99,
  },
  {
    id: 'fraggle', title: 'Fraggle Rock: Back to the Rock', type: 'kids', year: 2022, length: '2 Seasons',
    genre: 'Kids', rating: 'TV-Y', emoji: '🎸',
    poster: 'linear-gradient(165deg,#ff7043,#ffd54f)',
    backdrop: 'linear-gradient(160deg,#ff8a65,#ffd54f 60%,#c17900)',
    desc: 'Gobo, Red, Wembley, Mokey and Boober are back for all-new adventures, songs, and gorgs in the magical world of Fraggle Rock.',
    owned: false, price: 2.99,
  },
  {
    id: 'stillwater', title: 'Stillwater', type: 'kids', year: 2020, length: '3 Seasons',
    genre: 'Kids', rating: 'TV-Y', emoji: '🐼',
    poster: 'linear-gradient(165deg,#66bb6a,#26c6da)',
    backdrop: 'linear-gradient(160deg,#81c784,#26c6da 60%,#00696b)',
    desc: 'Siblings Karl, Addy and Michael learn mindfulness and kindness from their wise next-door neighbor, a panda named Stillwater.',
    owned: false, price: 2.99,
  },
  {
    id: 'helpsters', title: 'Helpsters', type: 'kids', year: 2020, length: '3 Seasons',
    genre: 'Kids', rating: 'TV-Y', emoji: '🧩',
    poster: 'linear-gradient(165deg,#ec407a,#ffca28)',
    backdrop: 'linear-gradient(160deg,#f06292,#ffca28 60%,#b28704)',
    desc: 'A team of vibrant monsters teaches pre-coding skills and problem solving — because everything starts with a plan!',
    owned: false, price: 2.99,
  },
  {
    id: 'wolfboy', title: 'Wolfboy and the Everything Factory', type: 'kids', year: 2021, length: '2 Seasons',
    genre: 'Kids', rating: 'TV-Y7', emoji: '🐺',
    poster: 'linear-gradient(165deg,#ab47bc,#42a5f5)',
    backdrop: 'linear-gradient(160deg,#ba68c8,#42a5f5 60%,#14508a)',
    desc: 'An oddball dreamer discovers a magical realm at the center of the Earth where the Sprytes make everything in the human world.',
    owned: false, price: 2.99,
  },
]

export const byId = (id) => TITLES.find((t) => t.id === id)

// Default Up Next queue: title id + playback progress (0–100) + episode label.
export const UP_NEXT_SEED = [
  { id: 'severance', progress: 62, ep: 'S2:E3 “Who Is Alive?”' },
  { id: 'kotfm', progress: 28, ep: null },
  { id: 'ted-lasso', progress: 85, ep: 'S3:E12 “So Long, Farewell”' },
  { id: 'silo', progress: 12, ep: 'S2:E1 “The Engineer”' },
]
